In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [ ]:
arr2d = np.array([[1,2], [3,4]])
arr2d

array([[1, 2],
       [3, 4]])

In [ ]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a = np.arange(21)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [ ]:
np.arange(2, 11, 2)

array([ 2,  4,  6,  8, 10])

In [ ]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [ ]:
np.arange(5, 51, 5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [ ]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
a.reshape((3,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [ ]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
a.shape

(12,)

In [ ]:
a.ndim

1

In [ ]:
arr2d.shape

(2, 2)

In [ ]:
arr2d.ndim

2

In [ ]:
arr2d.size

4

In [ ]:
a.dtype

dtype('int64')

In [ ]:
np.random.rand(3,4)

array([[0.6130239 , 0.31541098, 0.8599515 , 0.82260494],
       [0.59310025, 0.52817699, 0.85467813, 0.45979976],
       [0.75662049, 0.26276226, 0.72937301, 0.41986584]])

In [ ]:
np.random.randn(3,4)

array([[-0.2478512 ,  0.42409635, -0.75940313, -0.20803324],
       [-1.59842448, -0.72081819,  0.30877701, -0.25843951],
       [-0.70325385,  1.49944849, -0.69305773, -0.38479134]])

In [ ]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
np.concatenate((arr1, arr2))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:

np.sum(arr1)

np.int64(15)

In [ ]:
np.mean(arr1)

np.float64(3.0)

In [ ]:
np.median(arr1)

np.float64(3.0)

In [ ]:
np.max(arr1)

np.int64(5)

In [ ]:
np.min(arr1)

np.int64(1)

In [ ]:
arr1 = np.array([1,2,3,4,5])
np.std(arr1)

np.float64(1.4142135623730951)

In [ ]:
arr1 = np.array([-100,2,3,4,50])
np.std(arr1)

np.float64(49.3817780157823)

In [ ]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
arr1+arr2

array([ 7,  9, 11, 13, 15])

In [ ]:
np.dot(arr1,arr2)

np.int64(130)

In [ ]:
arr1 = np.array([1,2,3,4]).reshape((2,2))
arr2 = np.array([6,7,8,9]).reshape((2,2))

In [ ]:
arr3 = np.arange(9).reshape((3,3))
arr3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
np.transpose(arr3)

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [ ]:
arr1

array([[1, 2],
       [3, 4]])

In [ ]:
arr2

array([[6, 7],
       [8, 9]])